// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_checked`, `map_http_error`, `sanitize_filename`

/// Indexer'ın yeteneklerini sorgular (`?t=caps`). Bağlantı ve API anahtarı
/// doğrulaması için de kullanılır.
Future<IndexerCapsDto> newznabCheckCaps({required IndexerConfigDto config}) =>
    RustLib.instance.api.crateApiSearchNewznabCheckCaps(config: config);

/// Metin araması yapar (`?t=search&q=…`). Sonuçlar release rozetleriyle
/// birlikte döner; liste sırası indexer'ın sırasıdır.
Future<SearchPageDto> newznabSearch({
  required IndexerConfigDto config,
  required String query,
  required int limit,
  required int offset,
}) => RustLib.instance.api.crateApiSearchNewznabSearch(
  config: config,
  query: query,
  limit: limit,
  offset: offset,
);

/// Arama sonucunun NZB'sini geçici dizine indirir ve dosya yolunu döndürür.
/// Yanıtın gerçekten NZB olduğu kök öğe kokusuyla doğrulanır; HTML hata
/// sayfaları oynatıcıya kadar ilerleyemez.
Future<String> newznabDownloadNzb({
  required IndexerConfigDto config,
  required String nzbUrl,
  required String suggestedName,
}) => RustLib.instance.api.crateApiSearchNewznabDownloadNzb(
  config: config,
  nzbUrl: nzbUrl,
  suggestedName: suggestedName,
);

/// `?t=caps` özeti; UI hangi arama türlerinin açık olduğunu buna göre gösterir.
class IndexerCapsDto {
  final String? serverTitle;
  final bool searchAvailable;
  final bool tvSearchAvailable;
  final bool movieSearchAvailable;

  const IndexerCapsDto({
    this.serverTitle,
    required this.searchAvailable,
    required this.tvSearchAvailable,
    required this.movieSearchAvailable,
  });

  @override
  int get hashCode =>
      serverTitle.hashCode ^
      searchAvailable.hashCode ^
      tvSearchAvailable.hashCode ^
      movieSearchAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexerCapsDto &&
          runtimeType == other.runtimeType &&
          serverTitle == other.serverTitle &&
          searchAvailable == other.searchAvailable &&
          tvSearchAvailable == other.tvSearchAvailable &&
          movieSearchAvailable == other.movieSearchAvailable;
}

/// Dart'tan gelen indexer yapılandırması.
class IndexerConfigDto {
  /// Ör. `https://miatrix.example` (sonunda `/api` olabilir ya da olmayabilir).
  final String baseUrl;
  final String apiKey;

  const IndexerConfigDto({required this.baseUrl, required this.apiKey});

  @override
  int get hashCode => baseUrl.hashCode ^ apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexerConfigDto &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          apiKey == other.apiKey;
}

/// Tek arama sonucu. `nzb_url` API anahtarı içerebilir; loglanmamalıdır.
class SearchItemDto {
  final String title;
  final String nzbUrl;
  final String? infoUrl;
  final BigInt? sizeBytes;
  final PlatformInt64? publishedEpochSecs;

  /// Rust tarafında hazırlanan görüntü rozetleri: ["2160p","HEVC","DV",…].
  final List<String> badges;

  /// "movie" | "tv" | "other" — UI simgesi için.
  final String mediaKind;
  final int? season;
  final int? episode;
  final int? year;
  final String? group;

  const SearchItemDto({
    required this.title,
    required this.nzbUrl,
    this.infoUrl,
    this.sizeBytes,
    this.publishedEpochSecs,
    required this.badges,
    required this.mediaKind,
    this.season,
    this.episode,
    this.year,
    this.group,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      nzbUrl.hashCode ^
      infoUrl.hashCode ^
      sizeBytes.hashCode ^
      publishedEpochSecs.hashCode ^
      badges.hashCode ^
      mediaKind.hashCode ^
      season.hashCode ^
      episode.hashCode ^
      year.hashCode ^
      group.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchItemDto &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          nzbUrl == other.nzbUrl &&
          infoUrl == other.infoUrl &&
          sizeBytes == other.sizeBytes &&
          publishedEpochSecs == other.publishedEpochSecs &&
          badges == other.badges &&
          mediaKind == other.mediaKind &&
          season == other.season &&
          episode == other.episode &&
          year == other.year &&
          group == other.group;
}

class SearchPageDto {
  final BigInt? total;
  final List<SearchItemDto> items;

  const SearchPageDto({this.total, required this.items});

  @override
  int get hashCode => total.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SearchPageDto &&
          runtimeType == other.runtimeType &&
          total == other.total &&
          items == other.items;
}
