// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `url_encode_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

/// NZB'nin en büyük dosyası için localhost Range server'ı başlatır ve URL
/// döndürür. Bootstrap (ilk segmentle boyut öğrenme) bu çağrıda tamamlanır;
/// döndükten sonra URL hemen oynatılabilir.
///
/// Bu FRB fonksiyonu ayrı bir worker thread'de çalışır (UI bloklanmaz).
Future<StreamInfo> startStream({
  required ProviderConfigDto config,
  required String nzbPath,
}) => RustLib.instance.api.crateApiStreamingStartStream(
  config: config,
  nzbPath: nzbPath,
);

/// Dart'tan gelen sağlayıcı yapılandırması.
class ProviderConfigDto {
  final String host;
  final int port;
  final String username;
  final String password;
  final int maxConnections;

  const ProviderConfigDto({
    required this.host,
    required this.port,
    required this.username,
    required this.password,
    required this.maxConnections,
  });

  @override
  int get hashCode =>
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      maxConnections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProviderConfigDto &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          maxConnections == other.maxConnections;
}

/// Başlatılan stream'in oynatıcıya verilecek bilgileri.
class StreamInfo {
  /// media_kit'in açacağı localhost URL'i.
  final String url;

  /// Çözülmüş dosya boyutu (bayt).
  final BigInt size;
  final String filename;
  final int segmentCount;

  const StreamInfo({
    required this.url,
    required this.size,
    required this.filename,
    required this.segmentCount,
  });

  @override
  int get hashCode =>
      url.hashCode ^ size.hashCode ^ filename.hashCode ^ segmentCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StreamInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          size == other.size &&
          filename == other.filename &&
          segmentCount == other.segmentCount;
}
